
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul 18 2024 12:56:51 IST (Jul 18 2024 07:26:51 UTC)

// Verification Directory fv/voting_machine 

module voting_machine(clk, reset, mode, in_candidate_1, in_candidate_2,
     in_candidate_3, count_candidate_1, count_candidate_2,
     count_candidate_3, candidate_1, candidate_2, candidate_3, SE,
     scan_in, scan_out);
  input clk, reset, in_candidate_1, in_candidate_2, in_candidate_3, SE,
       scan_in;
  input [1:0] mode;
  output [7:0] count_candidate_1, count_candidate_2, count_candidate_3;
  output candidate_1, candidate_2, candidate_3, scan_out;
  wire clk, reset, in_candidate_1, in_candidate_2, in_candidate_3, SE,
       scan_in;
  wire [1:0] mode;
  wire [7:0] count_candidate_1, count_candidate_2, count_candidate_3;
  wire candidate_1, candidate_2, candidate_3, scan_out;
  wire [7:0] vote_1;
  wire [7:0] vote_2;
  wire [7:0] vote_3;
  wire [1:0] state;
  wire [1:0] next_state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_35, n_37, n_38, n_43, n_47;
  wire n_50, n_51, n_52, n_53, n_54, n_57, n_60, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99;
  assign candidate_3 = in_candidate_3;
  assign candidate_2 = in_candidate_2;
  assign candidate_1 = in_candidate_1;
  SDFFQX1 \vote_1_reg[7] (.CK (clk), .D (n_99), .SI (vote_1[6]), .SE
       (SE), .Q (vote_1[7]));
  SDFFQX1 \vote_2_reg[7] (.CK (clk), .D (n_98), .SI (vote_2[6]), .SE
       (SE), .Q (vote_2[7]));
  SDFFQX1 \vote_3_reg[7] (.CK (clk), .D (n_97), .SI (vote_3[6]), .SE
       (SE), .Q (scan_out));
  SDFFQX1 \vote_2_reg[6] (.CK (clk), .D (n_96), .SI (vote_2[5]), .SE
       (SE), .Q (vote_2[6]));
  SDFFQX1 \vote_3_reg[6] (.CK (clk), .D (n_95), .SI (vote_3[5]), .SE
       (SE), .Q (vote_3[6]));
  SDFFQX1 \vote_1_reg[6] (.CK (clk), .D (n_94), .SI (vote_1[5]), .SE
       (SE), .Q (vote_1[6]));
  NOR2BX1 g971__2398(.AN (n_90), .B (reset), .Y (n_99));
  NOR2BX1 g969__5107(.AN (n_93), .B (reset), .Y (n_98));
  NOR2BX1 g970__6260(.AN (n_91), .B (reset), .Y (n_97));
  SDFFQX1 \vote_1_reg[5] (.CK (clk), .D (n_78), .SI (vote_1[4]), .SE
       (SE), .Q (vote_1[5]));
  SDFFQX1 \vote_3_reg[5] (.CK (clk), .D (n_80), .SI (vote_3[4]), .SE
       (SE), .Q (vote_3[5]));
  SDFFQX1 \vote_2_reg[5] (.CK (clk), .D (n_82), .SI (vote_2[4]), .SE
       (SE), .Q (vote_2[5]));
  SDFFQX1 \state_reg[1] (.CK (clk), .D (n_83), .SI (state[0]), .SE
       (SE), .Q (state[1]));
  INVXL g978(.A (n_88), .Y (n_96));
  INVXL g980(.A (n_85), .Y (n_95));
  INVXL g981(.A (n_92), .Y (n_94));
  SDFFQX1 \vote_2_reg[4] (.CK (clk), .D (n_74), .SI (vote_2[3]), .SE
       (SE), .Q (vote_2[4]));
  SDFFQX1 \vote_3_reg[4] (.CK (clk), .D (n_75), .SI (vote_3[3]), .SE
       (SE), .Q (vote_3[4]));
  SDFFQX1 \vote_1_reg[4] (.CK (clk), .D (n_76), .SI (vote_1[3]), .SE
       (SE), .Q (vote_1[4]));
  XNOR2X1 g975__4319(.A (n_86), .B (vote_2[7]), .Y (n_93));
  OAI211X1 g983__8428(.A0 (n_77), .A1 (vote_1[6]), .B0 (n_87), .C0
       (n_89), .Y (n_92));
  XNOR2X1 g976__5526(.A (n_84), .B (scan_out), .Y (n_91));
  XNOR2X1 g977__6783(.A (n_89), .B (vote_1[7]), .Y (n_90));
  OAI211X1 g979__3680(.A0 (n_81), .A1 (vote_2[6]), .B0 (n_87), .C0
       (n_86), .Y (n_88));
  OAI211X1 g982__1617(.A0 (n_79), .A1 (vote_3[6]), .B0 (n_87), .C0
       (n_84), .Y (n_85));
  NOR2BX1 g1036__2802(.AN (next_state[1]), .B (reset), .Y (n_83));
  AOI211XL g990__1705(.A0 (n_72), .A1 (n_67), .B0 (reset), .C0 (n_81),
       .Y (n_82));
  AOI211XL g991__5122(.A0 (n_70), .A1 (n_66), .B0 (reset), .C0 (n_79),
       .Y (n_80));
  SDFFQX1 \vote_2_reg[3] (.CK (clk), .D (n_54), .SI (vote_2[2]), .SE
       (SE), .Q (vote_2[3]));
  SDFFQX1 \vote_1_reg[3] (.CK (clk), .D (n_51), .SI (vote_1[2]), .SE
       (SE), .Q (vote_1[3]));
  AOI211XL g992__8246(.A0 (n_68), .A1 (n_65), .B0 (reset), .C0 (n_77),
       .Y (n_78));
  SDFFQX1 \vote_3_reg[3] (.CK (clk), .D (n_64), .SI (vote_3[2]), .SE
       (SE), .Q (vote_3[3]));
  INVXL g1001(.A (n_69), .Y (n_76));
  INVXL g1000(.A (n_71), .Y (n_75));
  NAND2X1 g987__7098(.A (n_81), .B (vote_2[6]), .Y (n_86));
  NAND2X1 g988__6131(.A (n_77), .B (vote_1[6]), .Y (n_89));
  INVXL g999(.A (n_73), .Y (n_74));
  NAND2X1 g989__1881(.A (n_79), .B (vote_3[6]), .Y (n_84));
  SDFFQX1 \vote_3_reg[2] (.CK (clk), .D (n_37), .SI (vote_3[1]), .SE
       (SE), .Q (vote_3[2]));
  SDFFQX1 \vote_2_reg[2] (.CK (clk), .D (n_35), .SI (vote_2[1]), .SE
       (SE), .Q (vote_2[2]));
  SDFFQX1 \vote_1_reg[2] (.CK (clk), .D (n_38), .SI (vote_1[1]), .SE
       (SE), .Q (vote_1[2]));
  OAI211X1 g1002__5115(.A0 (n_52), .A1 (vote_2[4]), .B0 (n_87), .C0
       (n_72), .Y (n_73));
  OAI211X1 g1003__7482(.A0 (n_63), .A1 (vote_3[4]), .B0 (n_87), .C0
       (n_70), .Y (n_71));
  SDFFQX1 \next_state_reg[1] (.CK (clk), .D (n_25), .SI
       (next_state[0]), .SE (SE), .Q (next_state[1]));
  OAI211X1 g1004__4733(.A0 (n_50), .A1 (vote_1[4]), .B0 (n_87), .C0
       (n_68), .Y (n_69));
  SDFFQX1 \next_state_reg[0] (.CK (clk), .D (n_26), .SI (scan_in), .SE
       (SE), .Q (next_state[0]));
  NOR2X1 g996__6161(.A (n_72), .B (n_67), .Y (n_81));
  NOR2X1 g997__9315(.A (n_70), .B (n_66), .Y (n_79));
  NOR2X1 g998__9945(.A (n_68), .B (n_65), .Y (n_77));
  AOI211XL g1011__2883(.A0 (n_21), .A1 (n_57), .B0 (reset), .C0 (n_63),
       .Y (n_64));
  NOR2XL g1068__2346(.A (n_53), .B (n_60), .Y (count_candidate_2[3]));
  NOR2XL g1047__1666(.A (n_11), .B (n_60), .Y (count_candidate_2[1]));
  NOR2XL g1053__7410(.A (n_66), .B (n_60), .Y (count_candidate_3[5]));
  NOR2XL g1054__6417(.A (n_57), .B (n_60), .Y (count_candidate_3[3]));
  NOR2XL g1042__5477(.A (n_17), .B (n_60), .Y (count_candidate_3[1]));
  NOR2XL g1056__2398(.A (n_67), .B (n_60), .Y (count_candidate_2[5]));
  SDFFQX1 \vote_1_reg[1] (.CK (clk), .D (n_15), .SI (vote_1[0]), .SE
       (SE), .Q (vote_1[1]));
  AOI211XL g1013__5107(.A0 (n_19), .A1 (n_53), .B0 (reset), .C0 (n_52),
       .Y (n_54));
  SDFFQX1 \vote_3_reg[1] (.CK (clk), .D (n_18), .SI (vote_3[0]), .SE
       (SE), .Q (vote_3[1]));
  SDFFQX1 \vote_2_reg[1] (.CK (clk), .D (n_12), .SI (vote_2[0]), .SE
       (SE), .Q (vote_2[1]));
  AOI211XL g1012__6260(.A0 (n_23), .A1 (n_47), .B0 (reset), .C0 (n_50),
       .Y (n_51));
  NOR2XL g1044__4319(.A (n_65), .B (n_60), .Y (count_candidate_1[5]));
  NOR2XL g1067__8428(.A (n_47), .B (n_60), .Y (count_candidate_1[3]));
  NOR2XL g1043__5526(.A (n_14), .B (n_60), .Y (count_candidate_1[1]));
  AND2XL g1049__6783(.A (vote_2[6]), .B (n_43), .Y
       (count_candidate_2[6]));
  AND2XL g1052__3680(.A (vote_3[6]), .B (n_43), .Y
       (count_candidate_3[6]));
  AND2XL g1062__1617(.A (vote_3[0]), .B (n_43), .Y
       (count_candidate_3[0]));
  AND2XL g1071__2802(.A (vote_2[2]), .B (n_43), .Y
       (count_candidate_2[2]));
  AND2XL g1045__1705(.A (vote_2[0]), .B (n_43), .Y
       (count_candidate_2[0]));
  AND2XL g1046__5122(.A (vote_1[4]), .B (n_43), .Y
       (count_candidate_1[4]));
  INVXL g1020(.A (n_24), .Y (n_38));
  INVXL g1021(.A (n_22), .Y (n_37));
  NAND2X1 g1010__8246(.A (n_63), .B (vote_3[4]), .Y (n_70));
  NAND2X1 g1008__7098(.A (n_52), .B (vote_2[4]), .Y (n_72));
  SDFFQX1 \vote_1_reg[0] (.CK (clk), .D (n_8), .SI (state[1]), .SE
       (SE), .Q (vote_1[0]));
  NAND2X1 g1009__6131(.A (n_50), .B (vote_1[4]), .Y (n_68));
  AND2XL g1066__1881(.A (vote_2[7]), .B (n_43), .Y
       (count_candidate_2[7]));
  INVXL g1022(.A (n_20), .Y (n_35));
  AND2XL g1048__5115(.A (scan_out), .B (n_43), .Y
       (count_candidate_3[7]));
  AND2XL g1064__7482(.A (vote_2[4]), .B (n_43), .Y
       (count_candidate_2[4]));
  AND2XL g1050__4733(.A (vote_3[4]), .B (n_43), .Y
       (count_candidate_3[4]));
  AND2XL g1063__6161(.A (vote_1[7]), .B (n_43), .Y
       (count_candidate_1[7]));
  AND2XL g1057__9315(.A (vote_1[2]), .B (n_43), .Y
       (count_candidate_1[2]));
  AND2XL g1055__9945(.A (vote_3[2]), .B (n_43), .Y
       (count_candidate_3[2]));
  AND2XL g1051__2883(.A (vote_1[0]), .B (n_43), .Y
       (count_candidate_1[0]));
  AND2XL g1069__2346(.A (vote_1[6]), .B (n_43), .Y
       (count_candidate_1[6]));
  SDFFQX1 \vote_2_reg[0] (.CK (clk), .D (n_9), .SI (vote_1[7]), .SE
       (SE), .Q (vote_2[0]));
  SDFFQX1 \vote_3_reg[0] (.CK (clk), .D (n_7), .SI (vote_2[7]), .SE
       (SE), .Q (vote_3[0]));
  NOR4BX1 g1061__1666(.AN (mode[0]), .B (mode[1]), .C (state[0]), .D
       (state[1]), .Y (n_26));
  NOR4BX1 g1065__7410(.AN (mode[1]), .B (mode[0]), .C (state[0]), .D
       (state[1]), .Y (n_25));
  INVXL g1077(.A (n_43), .Y (n_60));
  OAI211X1 g1023__6417(.A0 (n_13), .A1 (vote_1[2]), .B0 (n_87), .C0
       (n_23), .Y (n_24));
  OAI211X1 g1024__5477(.A0 (n_16), .A1 (vote_3[2]), .B0 (n_87), .C0
       (n_21), .Y (n_22));
  OAI211X1 g1025__2398(.A0 (n_10), .A1 (vote_2[2]), .B0 (n_87), .C0
       (n_19), .Y (n_20));
  NOR2X1 g1017__5107(.A (n_19), .B (n_53), .Y (n_52));
  NOR2BX1 g1078__6260(.AN (state[1]), .B (state[0]), .Y (n_43));
  NOR2X1 g1018__4319(.A (n_21), .B (n_57), .Y (n_63));
  NOR2X1 g1019__8428(.A (n_23), .B (n_47), .Y (n_50));
  AOI211XL g1032__5526(.A0 (n_3), .A1 (n_17), .B0 (reset), .C0 (n_16),
       .Y (n_18));
  AOI211XL g1033__6783(.A0 (n_1), .A1 (n_14), .B0 (reset), .C0 (n_13),
       .Y (n_15));
  AOI211XL g1034__3680(.A0 (n_5), .A1 (n_11), .B0 (reset), .C0 (n_10),
       .Y (n_12));
  INVXL g1058(.A (n_6), .Y (n_9));
  NAND2X1 g1035__1617(.A (n_10), .B (vote_2[2]), .Y (n_19));
  NAND2X1 g1030__2802(.A (n_16), .B (vote_3[2]), .Y (n_21));
  INVXL g1060(.A (n_2), .Y (n_8));
  INVXL g1059(.A (n_4), .Y (n_7));
  NAND2X1 g1031__1705(.A (n_13), .B (vote_1[2]), .Y (n_23));
  SDFFQX1 \state_reg[0] (.CK (clk), .D (n_0), .SI (next_state[1]), .SE
       (SE), .Q (state[0]));
  OAI211X1 g1070__5122(.A0 (in_candidate_2), .A1 (vote_2[0]), .B0
       (n_87), .C0 (n_5), .Y (n_6));
  OAI211X1 g1072__8246(.A0 (in_candidate_3), .A1 (vote_3[0]), .B0
       (n_87), .C0 (n_3), .Y (n_4));
  OAI211X1 g1073__7098(.A0 (in_candidate_1), .A1 (vote_1[0]), .B0
       (n_87), .C0 (n_1), .Y (n_2));
  NOR2X1 g1074__6131(.A (n_5), .B (n_11), .Y (n_10));
  NOR2X1 g1075__1881(.A (n_1), .B (n_14), .Y (n_13));
  NOR2X1 g1076__5115(.A (n_3), .B (n_17), .Y (n_16));
  NAND2X1 g1081__7482(.A (in_candidate_3), .B (vote_3[0]), .Y (n_3));
  NAND2X1 g1082__4733(.A (in_candidate_1), .B (vote_1[0]), .Y (n_1));
  NOR2BX1 g1080__6161(.AN (next_state[0]), .B (reset), .Y (n_0));
  NAND2X1 g1083__9315(.A (in_candidate_2), .B (vote_2[0]), .Y (n_5));
  INVX1 g1084(.A (vote_2[5]), .Y (n_67));
  INVX1 g1091(.A (vote_1[3]), .Y (n_47));
  INVX1 g1088(.A (vote_1[5]), .Y (n_65));
  INVX1 g1085(.A (vote_2[3]), .Y (n_53));
  INVX1 g1093(.A (reset), .Y (n_87));
  INVX1 g1090(.A (vote_1[1]), .Y (n_14));
  INVX1 g1092(.A (vote_3[5]), .Y (n_66));
  INVX1 g1087(.A (vote_2[1]), .Y (n_11));
  INVX1 g1086(.A (vote_3[1]), .Y (n_17));
  INVX1 g1089(.A (vote_3[3]), .Y (n_57));
endmodule

