
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul 18 2024 12:43:40 IST (Jul 18 2024 07:13:40 UTC)

// Verification Directory fv/voting_machine 

module voting_machine(clk, reset, mode, in_candidate_1, in_candidate_2,
     in_candidate_3, count_candidate_1, count_candidate_2,
     count_candidate_3, candidate_1, candidate_2, candidate_3);
  input clk, reset, in_candidate_1, in_candidate_2, in_candidate_3;
  input [1:0] mode;
  output [7:0] count_candidate_1, count_candidate_2, count_candidate_3;
  output candidate_1, candidate_2, candidate_3;
  wire clk, reset, in_candidate_1, in_candidate_2, in_candidate_3;
  wire [1:0] mode;
  wire [7:0] count_candidate_1, count_candidate_2, count_candidate_3;
  wire candidate_1, candidate_2, candidate_3;
  wire [7:0] vote_1;
  wire [7:0] vote_2;
  wire [7:0] vote_3;
  wire [1:0] state;
  wire [1:0] next_state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_23, n_27, n_31;
  wire n_33, n_34, n_35, n_40, n_44, n_48, n_52, n_54;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98;
  assign candidate_3 = in_candidate_3;
  assign candidate_2 = in_candidate_2;
  assign candidate_1 = in_candidate_1;
  DFFQXL \vote_1_reg[7] (.CK (clk), .D (n_98), .Q (vote_1[7]));
  DFFQXL \vote_2_reg[7] (.CK (clk), .D (n_97), .Q (vote_2[7]));
  DFFQXL \vote_3_reg[7] (.CK (clk), .D (n_96), .Q (vote_3[7]));
  DFFHQX1 \vote_2_reg[6] (.CK (clk), .D (n_95), .Q (vote_2[6]));
  DFFHQX1 \vote_3_reg[6] (.CK (clk), .D (n_94), .Q (vote_3[6]));
  DFFHQX1 \vote_1_reg[6] (.CK (clk), .D (n_93), .Q (vote_1[6]));
  NOR2BX1 g971__2398(.AN (n_90), .B (reset), .Y (n_98));
  NOR2BX1 g969__5107(.AN (n_92), .B (reset), .Y (n_97));
  NOR2BX1 g970__6260(.AN (n_91), .B (reset), .Y (n_96));
  NOR2X1 g978__4319(.A (reset), .B (n_89), .Y (n_95));
  NOR2X1 g979__8428(.A (reset), .B (n_87), .Y (n_94));
  NOR2X1 g980__5526(.A (reset), .B (n_85), .Y (n_93));
  XNOR2X1 g975__6783(.A (n_88), .B (vote_2[7]), .Y (n_92));
  XNOR2X1 g976__3680(.A (n_86), .B (vote_3[7]), .Y (n_91));
  XNOR2X1 g977__1617(.A (n_84), .B (vote_1[7]), .Y (n_90));
  DFFQXL \vote_2_reg[5] (.CK (clk), .D (n_83), .Q (vote_2[5]));
  DFFQXL \vote_3_reg[5] (.CK (clk), .D (n_81), .Q (vote_3[5]));
  DFFQXL \vote_1_reg[5] (.CK (clk), .D (n_79), .Q (vote_1[5]));
  OAI21X1 g984__2802(.A0 (n_82), .A1 (vote_2[6]), .B0 (n_88), .Y
       (n_89));
  OAI21X1 g985__1705(.A0 (n_80), .A1 (vote_3[6]), .B0 (n_86), .Y
       (n_87));
  OAI21X1 g986__5122(.A0 (n_78), .A1 (vote_1[6]), .B0 (n_84), .Y
       (n_85));
  DFFHQX1 \vote_2_reg[4] (.CK (clk), .D (n_75), .Q (vote_2[4]));
  DFFHQX1 \vote_3_reg[4] (.CK (clk), .D (n_77), .Q (vote_3[4]));
  DFFHQX1 \vote_1_reg[4] (.CK (clk), .D (n_76), .Q (vote_1[4]));
  AOI211XL g990__8246(.A0 (n_69), .A1 (n_68), .B0 (reset), .C0 (n_82),
       .Y (n_83));
  AOI211XL g991__7098(.A0 (n_73), .A1 (n_67), .B0 (reset), .C0 (n_80),
       .Y (n_81));
  AOI211XL g992__6131(.A0 (n_71), .A1 (n_66), .B0 (reset), .C0 (n_78),
       .Y (n_79));
  NOR2X1 g1000__1881(.A (reset), .B (n_74), .Y (n_77));
  NOR2X1 g1001__5115(.A (reset), .B (n_72), .Y (n_76));
  NAND2X1 g987__7482(.A (n_82), .B (vote_2[6]), .Y (n_88));
  NOR2X1 g999__4733(.A (reset), .B (n_70), .Y (n_75));
  NAND2X1 g989__6161(.A (n_80), .B (vote_3[6]), .Y (n_86));
  NAND2X1 g988__9315(.A (n_78), .B (vote_1[6]), .Y (n_84));
  DFFQXL \vote_1_reg[3] (.CK (clk), .D (n_62), .Q (vote_1[3]));
  DFFQXL \vote_2_reg[3] (.CK (clk), .D (n_60), .Q (vote_2[3]));
  DFFQXL \vote_3_reg[3] (.CK (clk), .D (n_64), .Q (vote_3[3]));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_65), .Q (state[1]));
  OAI21X1 g1007__9945(.A0 (n_63), .A1 (vote_3[4]), .B0 (n_73), .Y
       (n_74));
  OAI21X1 g1006__2883(.A0 (n_61), .A1 (vote_1[4]), .B0 (n_71), .Y
       (n_72));
  OAI21X1 g1005__2346(.A0 (n_59), .A1 (vote_2[4]), .B0 (n_69), .Y
       (n_70));
  DFFHQX1 \vote_1_reg[2] (.CK (clk), .D (n_58), .Q (vote_1[2]));
  NOR2X1 g996__1666(.A (n_69), .B (n_68), .Y (n_82));
  DFFHQX1 \vote_2_reg[2] (.CK (clk), .D (n_56), .Q (vote_2[2]));
  DFFHQX1 \vote_3_reg[2] (.CK (clk), .D (n_57), .Q (vote_3[2]));
  NOR2X1 g997__7410(.A (n_73), .B (n_67), .Y (n_80));
  NOR2X1 g998__6417(.A (n_71), .B (n_66), .Y (n_78));
  NOR2BX1 g1036__5477(.AN (next_state[1]), .B (reset), .Y (n_65));
  AOI211XL g1011__2398(.A0 (n_34), .A1 (n_44), .B0 (reset), .C0 (n_63),
       .Y (n_64));
  AOI211XL g1012__5107(.A0 (n_35), .A1 (n_54), .B0 (reset), .C0 (n_61),
       .Y (n_62));
  AOI211XL g1013__6260(.A0 (n_33), .A1 (n_48), .B0 (reset), .C0 (n_59),
       .Y (n_60));
  NAND2X1 g1008__4319(.A (n_59), .B (vote_2[4]), .Y (n_69));
  NAND2X1 g1009__8428(.A (n_61), .B (vote_1[4]), .Y (n_71));
  NAND2X1 g1010__5526(.A (n_63), .B (vote_3[4]), .Y (n_73));
  NOR2X1 g1020__6783(.A (reset), .B (n_27), .Y (n_58));
  NOR2X1 g1021__3680(.A (reset), .B (n_31), .Y (n_57));
  NOR2X1 g1022__1617(.A (reset), .B (n_23), .Y (n_56));
  NOR2XL g1064__2802(.A (n_54), .B (n_52), .Y (count_candidate_1[3]));
  DFFQXL \vote_2_reg[1] (.CK (clk), .D (n_20), .Q (vote_2[1]));
  DFFQXL \vote_3_reg[1] (.CK (clk), .D (n_15), .Q (vote_3[1]));
  DFFQXL \vote_1_reg[1] (.CK (clk), .D (n_12), .Q (vote_1[1]));
  DFFQXL \next_state_reg[0] (.CK (clk), .D (n_17), .Q (next_state[0]));
  NOR2XL g1044__1705(.A (n_66), .B (n_52), .Y (count_candidate_1[5]));
  DFFQXL \next_state_reg[1] (.CK (clk), .D (n_16), .Q (next_state[1]));
  NOR2XL g1042__5122(.A (n_14), .B (n_52), .Y (count_candidate_3[1]));
  NOR2XL g1056__8246(.A (n_68), .B (n_52), .Y (count_candidate_2[5]));
  NOR2XL g1065__7098(.A (n_48), .B (n_52), .Y (count_candidate_2[3]));
  NOR2XL g1047__6131(.A (n_19), .B (n_52), .Y (count_candidate_2[1]));
  NOR2XL g1053__1881(.A (n_67), .B (n_52), .Y (count_candidate_3[5]));
  NOR2XL g1054__5115(.A (n_44), .B (n_52), .Y (count_candidate_3[3]));
  NOR2XL g1043__7482(.A (n_11), .B (n_52), .Y (count_candidate_1[1]));
  AND2XL g1068__4733(.A (vote_2[2]), .B (n_40), .Y
       (count_candidate_2[2]));
  AND2XL g1066__6161(.A (vote_1[6]), .B (n_40), .Y
       (count_candidate_1[6]));
  AND2XL g1055__9315(.A (vote_3[2]), .B (n_40), .Y
       (count_candidate_3[2]));
  AND2XL g1060__9945(.A (vote_1[7]), .B (n_40), .Y
       (count_candidate_1[7]));
  AND2XL g1052__2883(.A (vote_3[6]), .B (n_40), .Y
       (count_candidate_3[6]));
  AND2XL g1049__2346(.A (vote_2[6]), .B (n_40), .Y
       (count_candidate_2[6]));
  NOR2X1 g1019__1666(.A (n_35), .B (n_54), .Y (n_61));
  NOR2X1 g1018__7410(.A (n_34), .B (n_44), .Y (n_63));
  DFFHQX1 \vote_1_reg[0] (.CK (clk), .D (n_7), .Q (vote_1[0]));
  NOR2X1 g1017__6417(.A (n_33), .B (n_48), .Y (n_59));
  DFFHQX1 \vote_2_reg[0] (.CK (clk), .D (n_9), .Q (vote_2[0]));
  DFFHQX1 \vote_3_reg[0] (.CK (clk), .D (n_8), .Q (vote_3[0]));
  AND2XL g1048__5477(.A (vote_3[7]), .B (n_40), .Y
       (count_candidate_3[7]));
  OAI21X1 g1026__2398(.A0 (n_13), .A1 (vote_3[2]), .B0 (n_34), .Y
       (n_31));
  AND2XL g1063__5107(.A (vote_2[7]), .B (n_40), .Y
       (count_candidate_2[7]));
  AND2XL g1051__6260(.A (vote_1[0]), .B (n_40), .Y
       (count_candidate_1[0]));
  AND2XL g1061__4319(.A (vote_2[4]), .B (n_40), .Y
       (count_candidate_2[4]));
  OAI21X1 g1027__8428(.A0 (n_10), .A1 (vote_1[2]), .B0 (n_35), .Y
       (n_27));
  AND2XL g1046__5526(.A (vote_1[4]), .B (n_40), .Y
       (count_candidate_1[4]));
  AND2XL g1045__6783(.A (vote_2[0]), .B (n_40), .Y
       (count_candidate_2[0]));
  AND2XL g1050__3680(.A (vote_3[4]), .B (n_40), .Y
       (count_candidate_3[4]));
  OAI21X1 g1028__1617(.A0 (n_18), .A1 (vote_2[2]), .B0 (n_33), .Y
       (n_23));
  AND2XL g1059__2802(.A (vote_3[0]), .B (n_40), .Y
       (count_candidate_3[0]));
  AND2XL g1057__1705(.A (vote_1[2]), .B (n_40), .Y
       (count_candidate_1[2]));
  AOI211XL g1034__5122(.A0 (n_6), .A1 (n_19), .B0 (reset), .C0 (n_18),
       .Y (n_20));
  NOR4BX1 g1058__8246(.AN (mode[0]), .B (mode[1]), .C (state[0]), .D
       (state[1]), .Y (n_17));
  NOR4BX1 g1062__7098(.AN (mode[1]), .B (mode[0]), .C (state[0]), .D
       (state[1]), .Y (n_16));
  AOI211XL g1032__6131(.A0 (n_4), .A1 (n_14), .B0 (reset), .C0 (n_13),
       .Y (n_15));
  AOI211XL g1033__1881(.A0 (n_5), .A1 (n_11), .B0 (reset), .C0 (n_10),
       .Y (n_12));
  INVXL g1074(.A (n_40), .Y (n_52));
  NOR2X1 g1067__5115(.A (reset), .B (n_2), .Y (n_9));
  NOR2X1 g1069__7482(.A (reset), .B (n_1), .Y (n_8));
  NAND2X1 g1035__4733(.A (n_18), .B (vote_2[2]), .Y (n_33));
  NOR2X1 g1070__6161(.A (reset), .B (n_3), .Y (n_7));
  NAND2X1 g1031__9315(.A (n_10), .B (vote_1[2]), .Y (n_35));
  NAND2X1 g1030__9945(.A (n_13), .B (vote_3[2]), .Y (n_34));
  NOR2BX1 g1075__2883(.AN (state[1]), .B (state[0]), .Y (n_40));
  NOR2X1 g1071__2346(.A (n_6), .B (n_19), .Y (n_18));
  NOR2X1 g1072__1666(.A (n_5), .B (n_11), .Y (n_10));
  NOR2X1 g1073__7410(.A (n_4), .B (n_14), .Y (n_13));
  OAI21X1 g1078__6417(.A0 (in_candidate_1), .A1 (vote_1[0]), .B0 (n_5),
       .Y (n_3));
  OAI21X1 g1079__5477(.A0 (in_candidate_2), .A1 (vote_2[0]), .B0 (n_6),
       .Y (n_2));
  OAI21X1 g1076__2398(.A0 (in_candidate_3), .A1 (vote_3[0]), .B0 (n_4),
       .Y (n_1));
  DFFQXL \state_reg[0] (.CK (clk), .D (n_0), .Q (state[0]));
  NOR2BX1 g1080__5107(.AN (next_state[0]), .B (reset), .Y (n_0));
  NAND2X1 g1083__6260(.A (in_candidate_2), .B (vote_2[0]), .Y (n_6));
  NAND2X1 g1081__4319(.A (in_candidate_3), .B (vote_3[0]), .Y (n_4));
  NAND2X1 g1082__8428(.A (in_candidate_1), .B (vote_1[0]), .Y (n_5));
  INVX1 g1087(.A (vote_2[1]), .Y (n_19));
  INVX1 g1091(.A (vote_1[3]), .Y (n_54));
  INVX1 g1085(.A (vote_2[3]), .Y (n_48));
  INVX1 g1090(.A (vote_1[1]), .Y (n_11));
  INVX1 g1088(.A (vote_1[5]), .Y (n_66));
  INVX1 g1084(.A (vote_2[5]), .Y (n_68));
  INVX1 g1089(.A (vote_3[3]), .Y (n_44));
  INVX1 g1086(.A (vote_3[1]), .Y (n_14));
  INVX1 g1092(.A (vote_3[5]), .Y (n_67));
endmodule

